### ISSUE TITLE
operator: create version of API Operator that can use annotations (instead of CRDs)

### ISSUE THREAD

**Issue by LesterThomas** [tmforum-oda/oda-ca#93]
## Description

The current [APIOperatorIstio](https://github.com/tmforum-oda/oda-ca/tree/master/controllers/apiOperatorIstio) configures Istio (via VirtualService CRD) and Prometheus (via ServiceMonitor CRD). Some observability systems use annotations to mark a Pod as a target for scraping observability metrics.

This issue is to create a new operator (or modify the existing operator) to use annotations. Make the implementation flexible to allow different configurations.

**Comment by gjo-satec** [comment]
Hi Lester, I can't see clearly the point of what we are trying to achieve here.
Prometheus is shipped with some discovery services, among them a Kubernetes one that scrapes different elements like pods or services.
[Combining this discovery service with a relabeling functionality is easy to create scraping jobs automatically ](https://kevinfeng.github.io/post/kubernetes-sd-in-prometheus/)
That functionality is provided off the shelf by Prometheus, the ServiceMonitor CRD provide by the operator brings a convenient way to add the needed annotations, a kind of syntactic sugar, so we could probably get rid of it.
But what's your idea? Is it to define a set of annotations for ODA to add the Promethues observability annotations by ourselves?
Something more generic?
